name: Run Historico

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *" # roda todo dia 12h UTC (~9h BR)

jobs:
  run-historico:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc-dev
          pip install -r requirements.txt

      - name: Criar .env
        run: |
          echo "DB_SERVER=${{ secrets.DB_SERVER }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env

      - name: Run Historico
        run: python -c "from utils.Historico import Historico; Historico().get_valorOrdenadoCompleto()"
