name: Run Historico

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *" # todo dia às 12h UTC (~09h Brasília)

jobs:
  run-historico:
    runs-on: ubuntu-latest

    env:
      DB_SERVER: "localhost,1433"
      DB_NAME: "HistoricoDB"
      DB_USER: "sa"
      # A senha aqui DEVE ser a mesma definida no passo "Start SQL Server"
      DB_PASS: "Str0ngP@ssw0rd!"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1. Instala e inicia o SQL Server diretamente no runner (sem Docker)
      - name: Start SQL Server
        uses: givemind/setup-sql-server@v1.1
        with:
          sql-server-version: "2022-latest"
          sa-password: ${{ env.DB_PASS }} # Usa a senha definida acima

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 2. Instala as dependências de sistema e do Python
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y freetds-dev unixodbc-dev
          pip install -r requirements.txt
          pip install pymssql

      # 3. Cria o banco de dados dentro do SQL Server recém-instalado
      - name: Create Database
        run: |
          # O comando `sqlcmd` fica disponível após a Action "setup-sql-server"
          sqlcmd -S localhost -U sa -P "${{ env.DB_PASS }}" -Q "CREATE DATABASE [${{ env.DB_NAME }}];"

      # 4. (CRÍTICO) Popula o banco com tabelas e dados
      - name: Populate Database from schema.sql
        run: |
          # Este passo irá falhar se o arquivo 'schema.sql' não existir
          if [ -f "schema.sql" ]; then
            echo "Arquivo schema.sql encontrado. Executando..."
            sqlcmd -S localhost -U sa -P "${{ env.DB_PASS }}" -d "${{ env.DB_NAME }}" -i schema.sql
          else
            echo "AVISO: Arquivo schema.sql não encontrado. O script principal pode falhar se as tabelas não existirem."
          fi
          
      # 5. Roda o seu script principal
      - name: Run Historico
        run: python main.py
